# Generated by Django 2.1.1 on 2019-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_advanced', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luasstop',
            name='id',
        ),
        migrations.AlterField(
            model_name='luasstop',
            name='short_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
