# Generated by Django 2.1.1 on 2019-11-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_advanced', '0002_auto_20191122_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='luasstop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='luasstop',
            name='line',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='luasstop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='luasstop',
            name='long_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='luasstop',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='luasstop',
            name='trams',
            field=models.CharField(blank=True, max_length=950, null=True),
        ),
    ]
